defaults:
  - bdm: default
  - abc: default
  - _self_

# You can override specific values here

bdm:
  verbose: false
  lattice:
    size: 25
  output:
    frequency: 100.0
    max_time: 2000.0

arcade:
  cellular:
    volume_mu: 2250
    volume_sigma: 200
    apop_age_mu: 120960
    apop_age_sigma: 10080
    necrotic_fraction: 0.5
    accuracy: 0.8
    affinity: 0.5
    compression_tolerance: 0
  output:
    frequency: 100.0
    max_time: 14400.0

abc:
  output_frequency: 10
  epsilon: 1
  sobol_power: 1
  model_type: "ARCADE"
  targets:
    - metric: "doubling_time"
      value: 30
      weight: 1.0
  parameter_ranges:
    volume_sigma_range:
      min: 50
      max: 500
    apop_age_sigma_range:
      min: 5040
      max: 20160
    necrotic_fraction_range:
      min: 0.2
      max: 0.8
    accuracy:
      min: 0.5
      max: 1.0
    affinity:
      min: 0.3
      max: 0.7
    compression_tolerance:
      min: 4.35
      max: 4.35      
