defaults:
  - bdm: default
  - abc: default
  - _self_

# You can override specific values here

bdm:
  verbose: false
  lattice:
    size: 25
  output:
    frequency: 100.0
    max_time: 2000.0
abc:
  output_frequency: 10
  epsilon: 7
  sobol_power: 2
  model_type: "BDM"
