# Model parameters for Birth-Death-Migration simulation
verbose: true

lattice:
  size: 30
  initial_density: 0.05

rates:
  proliferate: 0.01
  death: 0.0025
  migrate: 0.1

output:
  frequency: 100.0
  max_time: 1200.0