epsilon: 0.05
output_frequency: 100
sobol_power: 5.0
output_dir: abc_results/
parameter_ranges:
  proliferate:
    min: 0.01
    max: 0.02
  death:
    min: 0.001
    max: 0.005
  migrate:
    min: 0.15
    max: 0.25